### ISSUE TITLE
cannot initial Unable to initialize module

### ISSUE THREAD

**Issue by lilien1010** [xxtea/xxtea-pecl#5]
pecl 安装之后
执行php -v 的时候提示

PHP Warning:  PHP Startup: xxtea: Unable to initialize module
Module compiled with build ID=API20121212,NTS,debug
PHP    compiled with build ID=API20121212,NTS
These options need to match
 in Unknown on line 0
PHP 5.5.27 (cli) (built: Aug 22 2015 18:20:44)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by andot** [comment]
可能是编译选项不一致吧
