### ISSUE TITLE
Version 1.4 from 2006 can infinite loop

### ISSUE THREAD

**Issue by David263** [xxtea/xxtea-pecl#7]
The PHP version of XXTEA by Ma Bingyao (which comes from website http://www.coolcode.cn/?p=128 which no longer exists) can loop infinitely at lines 37 and 66, depending on the parameters:

37 while ($n <= -2147483649) $n += 4294967296;
66 $mx = int32((($z >> 5 & 0x07ffffff) ^ $y << 2) + (($y >> 3 & 0x1fffffff) ^ $z << 4)) ^ int32(($sum ^ $y) + ($k[$p & 3 ^ $e] ^ $z));

I do not know yet if the PECL extension from 2016 (https://github.com/xxtea/xxtea-php/blob/master/xxtea.php) has this problem.

The Javascript version by the same author contains a coding error (wrong type of arguments for a function) in these lines:

        v[i] = String.fromCharCode(v[i] & 0xff,
                                   v[i] >>> 8 & 0xff,
                                   v[i] >>> 16 & 0xff,
                                   v[i] >>> 24 & 0xff);

fromCharCode requires16-bit (not 8-bit) Unicode characters.

Also, both versions omit the conversion to and from a hexadecimal string for convenient typical use.

**Comment by andot** [comment]
The new PHP version: https://github.com/xxtea/xxtea-php

The new JavaScript versions:
https://github.com/xxtea/xxtea-js
https://github.com/xxtea/xxtea-html5
https://github.com/xxtea/xxtea-nodejs
